import {
  Search, ShoppingBag, PenLine, MousePointerClick, Share2, Star,
  Link2, MapPin, Code2, Mail, BarChart3, LineChart,
} from "lucide-react";

export const ALL_SERVICES = [
  { slug: "seo", title: "Search Engine Optimization", short: "SEO", icon: Search,
    blurb: "Climb the rankings with technical SEO, content, and authority building that compounds.",
    bullets: ["Technical audits & site health", "Keyword & topical authority", "Link acquisition", "Local & international SEO"] },
  { slug: "ecommerce", title: "Ecommerce Marketing", short: "Ecommerce", icon: ShoppingBag,
    blurb: "Full-funnel growth for online stores — from acquisition to retention.",
    bullets: ["Shopify & WooCommerce growth", "Product feed optimization", "Lifecycle email & SMS", "Conversion-focused merchandising"] },
  { slug: "content", title: "Content Marketing Service", short: "Content", icon: PenLine,
    blurb: "Editorial-grade content that ranks, educates, and earns trust.",
    bullets: ["Content strategy & briefs", "Long-form & pillar pages", "Subject-matter expert writing", "Distribution & repurposing"] },
  { slug: "cro", title: "Conversion Rate Optimization", short: "CRO", icon: MousePointerClick,
    blurb: "Turn your existing traffic into more revenue with research-backed experiments.",
    bullets: ["UX & funnel audits", "A/B testing program", "Landing page design", "Heatmaps & session research"] },
  { slug: "social", title: "Social Media Marketing", short: "Social", icon: Share2,
    blurb: "Show up consistently where your audience already spends time.",
    bullets: ["Organic strategy & calendars", "Short-form video", "Community management", "Paid social campaigns"] },
  { slug: "reputation", title: "Reputation Management", short: "Reputation", icon: Star,
    blurb: "Own your brand narrative across every channel and review platform.",
    bullets: ["Review generation & response", "Brand SERP cleanup", "Crisis monitoring", "PR & thought leadership"] },
  { slug: "affiliate", title: "Affiliate Marketing Service", short: "Affiliate", icon: Link2,
    blurb: "Build a performance-based partner program that scales profitably.",
    bullets: ["Program setup & strategy", "Partner recruitment", "Commission structures", "Tracking & fraud prevention"] },
  { slug: "local", title: "Local Business Marketing", short: "Local", icon: MapPin,
    blurb: "Dominate your city. Win the map pack and the moments that matter.",
    bullets: ["Google Business Profile", "Local citations", "Review velocity", "Geo-targeted campaigns"] },
  { slug: "web", title: "Web & App Development", short: "Web & App", icon: Code2,
    blurb: "Fast, modern websites and apps built for SEO, speed, and conversion.",
    bullets: ["Headless & Jamstack", "Custom web apps", "Mobile (iOS / Android)", "Core Web Vitals & performance"] },
  { slug: "email", title: "Email Marketing Service", short: "Email", icon: Mail,
    blurb: "Lifecycle email & SMS that drives 30%+ of ecommerce revenue.",
    bullets: ["Klaviyo & HubSpot", "Welcome & abandonment flows", "Segmentation & personalization", "Deliverability & design"] },
  { slug: "ppc", title: "Pay Per Click Service", short: "PPC", icon: BarChart3,
    blurb: "Profitable paid media across Google, Meta, TikTok, and beyond.",
    bullets: ["Account architecture", "Creative iteration", "Bidding & budget pacing", "Tracking & attribution"] },
  { slug: "analysis", title: "Online Presence Analysis", short: "Analysis", icon: LineChart,
    blurb: "A clear, honest read on where your brand stands — and what to fix first.",
    bullets: ["Competitive teardown", "SEO & content audit", "Channel benchmarking", "90-day growth roadmap"] },
] as const;

export type Service = (typeof ALL_SERVICES)[number];
